version: "2"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: server
    depends_on:
      - sez-db
      - sez-redis
    volumes:
      - ./sez/upload:/server/upload
      - ./sez/src:/server/src
    ports:
      - "3000:3000"
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: client
    depends_on:
      - server
    environment:
      - BASE_URL=server
      - NODE_ENV=production
  sez-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: sez-nginx
    depends_on:
      - client
    environment:
      - NGINX_SERVER_NAME=localhost
      - CLIENT_HOST=client
      - CLIENT_PORT=8000
      - HOST=server
      - PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - "80:80"
  sez-db:
    image: postgres:12
    container_name: sez-db
    environment:
      POSTGRES_DB: sez
      POSTGRES_USER: sez
      POSTGRES_PASSWORD: sez
#    ports:
#      - "5432:5432"
    volumes:
      - sezdb:/var/lib/sezdb
  sez-redis:
    image: redis:5
    container_name: sez-redis
#    ports:
#      - "6379:6379"
volumes:
  sezdb:
