FROM node:14.15.0-alpine

ENV BASE_URL server
ENV BASE_URL_PORT 3000
ENV NODE_ENV local
WORKDIR /app
COPY sez-frontend-nuxt/package.json sez-frontend-nuxt/yarn.lock ./
RUN yarn install

COPY sez-frontend-nuxt .
RUN yarn build

EXPOSE 8000

CMD [ "yarn", "start" ]
