FROM node:16.18.1-alpine

WORKDIR /api
ENV NODE_ENV dev
COPY api/package.json api/yarn.lock ./
RUN yarn install

COPY api .
RUN cp .env.example .env
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start:prod" ]
