FROM node:16.18.1-alpine

ENV BASE_URL api
ENV BASE_URL_PORT 3000
ENV NODE_ENV local
WORKDIR /app
COPY tfd-blog/package.json tfd-blog/yarn.lock ./
RUN yarn install

COPY tfd-blog .
RUN yarn build

EXPOSE 7000

CMD [ "yarn", "start" ]
